import { ApiProperty } from '@nestjs/swagger';
import { User } from 'src/user/entities/user.entity';

export class LoginResponseDto {
  @ApiProperty({
    description: 'JWT generated by login',
    example: 'TOKEN_GENERATED_AUTHOMATICALLY',
  })
  token: string;

  @ApiProperty({
    description: "User's data authenticated",
  })
  user: User;
}
